"""Abstract base class for all simulated IoT devices."""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
import random


class BaseDevice(ABC):
    """Base class that every simulated sensor must inherit from.

    Subclasses implement ``generate_reading`` (normal data) and
    ``generate_anomaly`` (faulty data).  The ``get_telemetry`` method
    wraps either result in a standardised envelope that includes device
    metadata.
    """

    def __init__(
        self,
        device_id: str,
        device_type: str,
        sampling_interval: float,
    ) -> None:
        self.device_id = device_id
        self.device_type = device_type
        self.sampling_interval = sampling_interval

    @abstractmethod
    def generate_reading(self) -> dict:
        """Generate a single normal sensor reading.

        Returns:
            A dictionary containing the sensor-specific payload fields.
        """
        ...

    @abstractmethod
    def generate_anomaly(self) -> dict:
        """Generate an anomalous sensor reading.

        Returns:
            A dictionary containing anomalous sensor-specific payload fields.
        """
        ...

    def get_telemetry(self, anomaly: bool = False) -> dict:
        """Build a full telemetry message with metadata.

        Args:
            anomaly: If ``True``, the payload is generated by
                ``generate_anomaly`` instead of ``generate_reading``.

        Returns:
            A dictionary ready for JSON serialisation and MQTT publishing.
        """
        payload = self.generate_anomaly() if anomaly else self.generate_reading()
        return {
            "device_id": self.device_id,
            "device_type": self.device_type,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "payload": payload,
            "metadata": {
                "firmware_version": "1.0.0",
                "signal_strength": random.randint(-90, -30),
            },
        }
