apiVersion: v1
kind: Service
metadata:
  name: data-persistence
  namespace: iot-gateway
spec:
  selector:
    app: data-persistence
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
