"""Alert and anomaly detection models."""

from datetime import datetime
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(BaseModel):
    """An alert generated by the ML inference pipeline."""

    alert_id: UUID = Field(default_factory=uuid4)
    device_id: UUID
    alert_type: str = "anomaly_detected"
    severity: AlertSeverity = AlertSeverity.WARNING
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    anomaly_score: float = Field(..., ge=0.0, le=1.0)
    model_version: str = "unknown"
    details: dict = Field(default_factory=dict)

    def to_stream_dict(self) -> dict[str, str]:
        """Serialize to flat dict for Redis XADD."""
        return {
            "alert_id": str(self.alert_id),
            "device_id": str(self.device_id),
            "alert_type": self.alert_type,
            "severity": self.severity.value,
            "timestamp": self.timestamp.isoformat(),
            "anomaly_score": str(self.anomaly_score),
            "model_version": self.model_version,
            "details": self.model_dump_json(include={"details"}),
        }
